//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Client.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AD.Client.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Action_Accept {
            get {
                return ResourceManager.GetString("Action_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Action_AddToCart {
            get {
                return ResourceManager.GetString("Action_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string Action_Back_To_List {
            get {
                return ResourceManager.GetString("Action_Back_To_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Action_Chat {
            get {
                return ResourceManager.GetString("Action_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Action_Clear {
            get {
                return ResourceManager.GetString("Action_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Order.
        /// </summary>
        public static string Action_ConfirmOrder {
            get {
                return ResourceManager.GetString("Action_ConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit All Orders.
        /// </summary>
        public static string Action_ConfirmOrders {
            get {
                return ResourceManager.GetString("Action_ConfirmOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Action_Details {
            get {
                return ResourceManager.GetString("Action_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Action_Filter {
            get {
                return ResourceManager.GetString("Action_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Action_Follow {
            get {
                return ResourceManager.GetString("Action_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        public static string Action_Freeze {
            get {
                return ResourceManager.GetString("Action_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Action_Next {
            get {
                return ResourceManager.GetString("Action_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Action_Previous {
            get {
                return ResourceManager.GetString("Action_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Received.
        /// </summary>
        public static string Action_Receive {
            get {
                return ResourceManager.GetString("Action_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Action_Register {
            get {
                return ResourceManager.GetString("Action_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Action_Reject {
            get {
                return ResourceManager.GetString("Action_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here....
        /// </summary>
        public static string Action_Search {
            get {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        public static string Action_Search_OutOf {
            get {
                return ResourceManager.GetString("Action_Search_OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Action_Search_Shwoing {
            get {
                return ResourceManager.GetString("Action_Search_Shwoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please, Select from this List--.
        /// </summary>
        public static string Action_Select {
            get {
                return ResourceManager.GetString("Action_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Action_Send {
            get {
                return ResourceManager.GetString("Action_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFollow.
        /// </summary>
        public static string Action_UnFollow {
            get {
                return ResourceManager.GetString("Action_UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFreeze.
        /// </summary>
        public static string Action_UnFreeze {
            get {
                return ResourceManager.GetString("Action_UnFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Class_Category {
            get {
                return ResourceManager.GetString("Class_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Class_Chat {
            get {
                return ResourceManager.GetString("Class_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Class_City {
            get {
                return ResourceManager.GetString("Class_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Class_Country {
            get {
                return ResourceManager.GetString("Class_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Class_Currency {
            get {
                return ResourceManager.GetString("Class_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Class_Employee {
            get {
                return ResourceManager.GetString("Class_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measruing Unit.
        /// </summary>
        public static string Class_MeasruingUnit {
            get {
                return ResourceManager.GetString("Class_MeasruingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Class_Order {
            get {
                return ResourceManager.GetString("Class_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Class_PaymentMethod {
            get {
                return ResourceManager.GetString("Class_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Class_Product {
            get {
                return ResourceManager.GetString("Class_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Class_Store {
            get {
                return ResourceManager.GetString("Class_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Class_Tag {
            get {
                return ResourceManager.GetString("Class_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Received.
        /// </summary>
        public static string Event_Order_Closed {
            get {
                return ResourceManager.GetString("Event_Order_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status has Edited.
        /// </summary>
        public static string Event_Order_Edited {
            get {
                return ResourceManager.GetString("Event_Order_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an Order has Rejected.
        /// </summary>
        public static string Event_Order_Rejected {
            get {
                return ResourceManager.GetString("Event_Order_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Filter_From {
            get {
                return ResourceManager.GetString("Filter_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Filter_To {
            get {
                return ResourceManager.GetString("Filter_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new app..
        /// </summary>
        public static string Index_Welcome {
            get {
                return ResourceManager.GetString("Index_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A New Record has Added.
        /// </summary>
        public static string Message_Add {
            get {
                return ResourceManager.GetString("Message_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product to Cart.
        /// </summary>
        public static string Message_Add_Product_To_Cart {
            get {
                return ResourceManager.GetString("Message_Add_Product_To_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Freezed Successfully.
        /// </summary>
        public static string Message_Category_Freeze {
            get {
                return ResourceManager.GetString("Message_Category_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Unfreezed Successfully.
        /// </summary>
        public static string Message_Category_UnFreeze {
            get {
                return ResourceManager.GetString("Message_Category_UnFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Select Country and City.
        /// </summary>
        public static string Message_City_error {
            get {
                return ResourceManager.GetString("Message_City_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Record has Deleted.
        /// </summary>
        public static string Message_Delete {
            get {
                return ResourceManager.GetString("Message_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no records..
        /// </summary>
        public static string Message_Empty {
            get {
                return ResourceManager.GetString("Message_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but something went wrong.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully has been Added to your Favorites.
        /// </summary>
        public static string Message_Follow {
            get {
                return ResourceManager.GetString("Message_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed Succesfully.
        /// </summary>
        public static string Message_Freeze_Successful {
            get {
                return ResourceManager.GetString("Message_Freeze_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Attempt.
        /// </summary>
        public static string Message_Login_error {
            get {
                return ResourceManager.GetString("Message_Login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this Account has freezed.
        /// </summary>
        public static string Message_Login_Freezed {
            get {
                return ResourceManager.GetString("Message_Login_Freezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Message_Login_success {
            get {
                return ResourceManager.GetString("Message_Login_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Quantity For This Product is:.
        /// </summary>
        public static string Message_MinValue_err {
            get {
                return ResourceManager.GetString("Message_MinValue_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status has Updated Successfully.
        /// </summary>
        public static string Message_OrderUpdated {
            get {
                return ResourceManager.GetString("Message_OrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add a quantity without a price.
        /// </summary>
        public static string Message_Quantity_err {
            get {
                return ResourceManager.GetString("Message_Quantity_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, for Rate your Order!.
        /// </summary>
        public static string Message_Rate {
            get {
                return ResourceManager.GetString("Message_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please, Try using a PhoneNumber not used bedore.
        /// </summary>
        public static string Message_Register_error {
            get {
                return ResourceManager.GetString("Message_Register_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Successfully.
        /// </summary>
        public static string Message_Register_success {
            get {
                return ResourceManager.GetString("Message_Register_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles has Updated Successfully .
        /// </summary>
        public static string Message_RoleUpdated {
            get {
                return ResourceManager.GetString("Message_RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select from the List.
        /// </summary>
        public static string Message_Select_err {
            get {
                return ResourceManager.GetString("Message_Select_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is Accepted Successfully.
        /// </summary>
        public static string Message_Store_Accept {
            get {
                return ResourceManager.GetString("Message_Store_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is Freezed Successfully.
        /// </summary>
        public static string Message_Store_Freeze {
            get {
                return ResourceManager.GetString("Message_Store_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is Rejected Successfully.
        /// </summary>
        public static string Message_Store_Reject {
            get {
                return ResourceManager.GetString("Message_Store_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is UnFreezed Successfully.
        /// </summary>
        public static string Message_Store_UnFreeze {
            get {
                return ResourceManager.GetString("Message_Store_UnFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully has been Removed from your Favorites.
        /// </summary>
        public static string Message_UnFollow {
            get {
                return ResourceManager.GetString("Message_UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFreezed Succesfully.
        /// </summary>
        public static string Message_UnFreeze_Successful {
            get {
                return ResourceManager.GetString("Message_UnFreeze_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Record has Updated.
        /// </summary>
        public static string Message_Update {
            get {
                return ResourceManager.GetString("Message_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is UnFreezed Successfully.
        /// </summary>
        public static string Message_User_UnFreeze {
            get {
                return ResourceManager.GetString("Message_User_UnFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Already Exists.
        /// </summary>
        public static string Message_UserName_error {
            get {
                return ResourceManager.GetString("Message_UserName_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to accept the store?.
        /// </summary>
        public static string Modal_Confirm_Accept {
            get {
                return ResourceManager.GetString("Modal_Confirm_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the record?.
        /// </summary>
        public static string Modal_Confirm_Delete {
            get {
                return ResourceManager.GetString("Modal_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to freeze this Category?.
        /// </summary>
        public static string Modal_Confirm_Freeze_Category {
            get {
                return ResourceManager.GetString("Modal_Confirm_Freeze_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to freeze this Product?.
        /// </summary>
        public static string Modal_Confirm_Freeze_Product {
            get {
                return ResourceManager.GetString("Modal_Confirm_Freeze_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to freeze this Store?.
        /// </summary>
        public static string Modal_Confirm_Freeze_Store {
            get {
                return ResourceManager.GetString("Modal_Confirm_Freeze_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to freeze this account?.
        /// </summary>
        public static string Modal_Confirm_Freeze_User {
            get {
                return ResourceManager.GetString("Modal_Confirm_Freeze_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Modal_Confirm_No {
            get {
                return ResourceManager.GetString("Modal_Confirm_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject the store?.
        /// </summary>
        public static string Modal_Confirm_Reject {
            get {
                return ResourceManager.GetString("Modal_Confirm_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Unfreeze this Category?.
        /// </summary>
        public static string Modal_Confirm_UnFreeze_Category {
            get {
                return ResourceManager.GetString("Modal_Confirm_UnFreeze_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Unfreeze this Store?.
        /// </summary>
        public static string Modal_Confirm_UnFreeze_Store {
            get {
                return ResourceManager.GetString("Modal_Confirm_UnFreeze_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Unfreeze this User?.
        /// </summary>
        public static string Modal_Confirm_UnFreeze_User {
            get {
                return ResourceManager.GetString("Modal_Confirm_UnFreeze_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Modal_Confirm_Yes {
            get {
                return ResourceManager.GetString("Modal_Confirm_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string Navbar_Culture {
            get {
                return ResourceManager.GetString("Navbar_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Navbar_Login {
            get {
                return ResourceManager.GetString("Navbar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Navbar_Logout {
            get {
                return ResourceManager.GetString("Navbar_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Navbar_Register {
            get {
                return ResourceManager.GetString("Navbar_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audits.
        /// </summary>
        public static string NavMenu_Audits {
            get {
                return ResourceManager.GetString("NavMenu_Audits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Services.
        /// </summary>
        public static string NavMenu_BackgroundServices {
            get {
                return ResourceManager.GetString("NavMenu_BackgroundServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string NavMenu_Cart {
            get {
                return ResourceManager.GetString("NavMenu_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string NavMenu_Categories {
            get {
                return ResourceManager.GetString("NavMenu_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Products.
        /// </summary>
        public static string NavMenu_CategoryProducts {
            get {
                return ResourceManager.GetString("NavMenu_CategoryProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string NavMenu_Cities {
            get {
                return ResourceManager.GetString("NavMenu_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string NavMenu_Counter {
            get {
                return ResourceManager.GetString("NavMenu_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string NavMenu_Countries {
            get {
                return ResourceManager.GetString("NavMenu_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string NavMenu_Currencies {
            get {
                return ResourceManager.GetString("NavMenu_Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string NavMenu_Employees {
            get {
                return ResourceManager.GetString("NavMenu_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Log.
        /// </summary>
        public static string NavMenu_Errors_Log {
            get {
                return ResourceManager.GetString("NavMenu_Errors_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Categories.
        /// </summary>
        public static string NavMenu_FavouriteCategories {
            get {
                return ResourceManager.GetString("NavMenu_FavouriteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Stores.
        /// </summary>
        public static string NavMenu_FavouriteStores {
            get {
                return ResourceManager.GetString("NavMenu_FavouriteStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed Categories.
        /// </summary>
        public static string NavMenu_FreezedCategories {
            get {
                return ResourceManager.GetString("NavMenu_FreezedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed Products.
        /// </summary>
        public static string NavMenu_FreezedProducts {
            get {
                return ResourceManager.GetString("NavMenu_FreezedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed Stores.
        /// </summary>
        public static string NavMenu_FreezedStores {
            get {
                return ResourceManager.GetString("NavMenu_FreezedStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed Users.
        /// </summary>
        public static string NavMenu_FreezedUsers {
            get {
                return ResourceManager.GetString("NavMenu_FreezedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HangFire.
        /// </summary>
        public static string NavMenu_HangFire {
            get {
                return ResourceManager.GetString("NavMenu_HangFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavMenu_Home {
            get {
                return ResourceManager.GetString("NavMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measruing Units.
        /// </summary>
        public static string NavMenu_MeasruingUnits {
            get {
                return ResourceManager.GetString("NavMenu_MeasruingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string NavMenu_MyOrders {
            get {
                return ResourceManager.GetString("NavMenu_MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stores.
        /// </summary>
        public static string NavMenu_MyStores {
            get {
                return ResourceManager.GetString("NavMenu_MyStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NavMenu_Notifications {
            get {
                return ResourceManager.GetString("NavMenu_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string NavMenu_Orders {
            get {
                return ResourceManager.GetString("NavMenu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string NavMenu_PaymentMethods {
            get {
                return ResourceManager.GetString("NavMenu_PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string NavMenu_Products {
            get {
                return ResourceManager.GetString("NavMenu_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Admin Stores.
        /// </summary>
        public static string NavMenu_RequestAdminStores {
            get {
                return ResourceManager.GetString("NavMenu_RequestAdminStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Products.
        /// </summary>
        public static string NavMenu_StoreProducts {
            get {
                return ResourceManager.GetString("NavMenu_StoreProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string NavMenu_Stores {
            get {
                return ResourceManager.GetString("NavMenu_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger.
        /// </summary>
        public static string NavMenu_Swagger {
            get {
                return ResourceManager.GetString("NavMenu_Swagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string NavMenu_Tags {
            get {
                return ResourceManager.GetString("NavMenu_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string NavMenu_Users {
            get {
                return ResourceManager.GetString("NavMenu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result Found.
        /// </summary>
        public static string No_Result_Found {
            get {
                return ResourceManager.GetString("No_Result_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Admin.
        /// </summary>
        public static string Permission_Admin {
            get {
                return ResourceManager.GetString("Permission_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Comments.
        /// </summary>
        public static string Permission_ManageComments {
            get {
                return ResourceManager.GetString("Permission_ManageComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Orders.
        /// </summary>
        public static string Permission_ManageOrders {
            get {
                return ResourceManager.GetString("Permission_ManageOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Products.
        /// </summary>
        public static string Permission_ManageProducts {
            get {
                return ResourceManager.GetString("Permission_ManageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string PlaceHolder_Payment_Details {
            get {
                return ResourceManager.GetString("PlaceHolder_Payment_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        public static string Property_ActionType {
            get {
                return ResourceManager.GetString("Property_ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Property_Address {
            get {
                return ResourceManager.GetString("Property_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AffectedColumns.
        /// </summary>
        public static string Property_Affected_Columns {
            get {
                return ResourceManager.GetString("Property_Affected_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected Columns.
        /// </summary>
        public static string Property_AffectedColumns {
            get {
                return ResourceManager.GetString("Property_AffectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Year.
        /// </summary>
        public static string Property_BirthYear {
            get {
                return ResourceManager.GetString("Property_BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Property_Body {
            get {
                return ResourceManager.GetString("Property_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Property_Brand {
            get {
                return ResourceManager.GetString("Property_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Property_Category {
            get {
                return ResourceManager.GetString("Property_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryL1.
        /// </summary>
        public static string Property_CategoryL1 {
            get {
                return ResourceManager.GetString("Property_CategoryL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryL2.
        /// </summary>
        public static string Property_CategoryL2 {
            get {
                return ResourceManager.GetString("Property_CategoryL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryL3.
        /// </summary>
        public static string Property_CategoryL3 {
            get {
                return ResourceManager.GetString("Property_CategoryL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryL4.
        /// </summary>
        public static string Property_CategoryL4 {
            get {
                return ResourceManager.GetString("Property_CategoryL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Level.
        /// </summary>
        public static string Property_CategoryLevel {
            get {
                return ResourceManager.GetString("Property_CategoryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Property_Cities {
            get {
                return ResourceManager.GetString("Property_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Property_City {
            get {
                return ResourceManager.GetString("Property_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Property_Code {
            get {
                return ResourceManager.GetString("Property_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code.
        /// </summary>
        public static string Property_CodeStore {
            get {
                return ResourceManager.GetString("Property_CodeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Property_Colors {
            get {
                return ResourceManager.GetString("Property_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Property_ConfirmPassword {
            get {
                return ResourceManager.GetString("Property_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Property_Countries {
            get {
                return ResourceManager.GetString("Property_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Property_Country {
            get {
                return ResourceManager.GetString("Property_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Property_Currency {
            get {
                return ResourceManager.GetString("Property_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Notes.
        /// </summary>
        public static string Property_CustomerNote {
            get {
                return ResourceManager.GetString("Property_CustomerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Property_DateTime {
            get {
                return ResourceManager.GetString("Property_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string Property_DefaultCurrency {
            get {
                return ResourceManager.GetString("Property_DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Property_Description {
            get {
                return ResourceManager.GetString("Property_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description_ar.
        /// </summary>
        public static string Property_Description_ar {
            get {
                return ResourceManager.GetString("Property_Description_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description_en.
        /// </summary>
        public static string Property_Description_en {
            get {
                return ResourceManager.GetString("Property_Description_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description_fr.
        /// </summary>
        public static string Property_Description_fr {
            get {
                return ResourceManager.GetString("Property_Description_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description_ru.
        /// </summary>
        public static string Property_Description_ru {
            get {
                return ResourceManager.GetString("Property_Description_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description_tr.
        /// </summary>
        public static string Property_Description_tr {
            get {
                return ResourceManager.GetString("Property_Description_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Property_Email {
            get {
                return ResourceManager.GetString("Property_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Property_FirstName {
            get {
                return ResourceManager.GetString("Property_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Property_Id {
            get {
                return ResourceManager.GetString("Property_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Property_Image {
            get {
                return ResourceManager.GetString("Property_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image.
        /// </summary>
        public static string Property_Images {
            get {
                return ResourceManager.GetString("Property_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Property_LastName {
            get {
                return ResourceManager.GetString("Property_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدة القياس.
        /// </summary>
        public static string Property_MeasruingUnit {
            get {
                return ResourceManager.GetString("Property_MeasruingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Unit.
        /// </summary>
        public static string Property_MeasruingUnitId {
            get {
                return ResourceManager.GetString("Property_MeasruingUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value To Sell.
        /// </summary>
        public static string Property_MinValue {
            get {
                return ResourceManager.GetString("Property_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Property_Name {
            get {
                return ResourceManager.GetString("Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_ar.
        /// </summary>
        public static string Property_Name_ar {
            get {
                return ResourceManager.GetString("Property_Name_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_en.
        /// </summary>
        public static string Property_Name_en {
            get {
                return ResourceManager.GetString("Property_Name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_fr.
        /// </summary>
        public static string Property_Name_fr {
            get {
                return ResourceManager.GetString("Property_Name_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_ru.
        /// </summary>
        public static string Property_Name_ru {
            get {
                return ResourceManager.GetString("Property_Name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_tr.
        /// </summary>
        public static string Property_Name_tr {
            get {
                return ResourceManager.GetString("Property_Name_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Values.
        /// </summary>
        public static string Property_NewValues {
            get {
                return ResourceManager.GetString("Property_NewValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Property_Note {
            get {
                return ResourceManager.GetString("Property_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Values.
        /// </summary>
        public static string Property_OldValues {
            get {
                return ResourceManager.GetString("Property_OldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Property_OrderDate {
            get {
                return ResourceManager.GetString("Property_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Property_Password {
            get {
                return ResourceManager.GetString("Property_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Property_PaymentMethod {
            get {
                return ResourceManager.GetString("Property_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Property_Permissions {
            get {
                return ResourceManager.GetString("Property_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Property_PhoneNumber {
            get {
                return ResourceManager.GetString("Property_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Property_Price {
            get {
                return ResourceManager.GetString("Property_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price For First Quantity Per Unit.
        /// </summary>
        public static string Property_Price1 {
            get {
                return ResourceManager.GetString("Property_Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price For Second Quantity Per Unit.
        /// </summary>
        public static string Property_Price2 {
            get {
                return ResourceManager.GetString("Property_Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price For Third Quantity Per Unit.
        /// </summary>
        public static string Property_Price3 {
            get {
                return ResourceManager.GetString("Property_Price3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Property_Quantity {
            get {
                return ResourceManager.GetString("Property_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Quantity.
        /// </summary>
        public static string Property_Quantity1 {
            get {
                return ResourceManager.GetString("Property_Quantity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Quantity.
        /// </summary>
        public static string Property_Quantity2 {
            get {
                return ResourceManager.GetString("Property_Quantity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Quantity.
        /// </summary>
        public static string Property_Quantity3 {
            get {
                return ResourceManager.GetString("Property_Quantity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Property_Rate {
            get {
                return ResourceManager.GetString("Property_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Property_Rating {
            get {
                return ResourceManager.GetString("Property_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Property_Roles {
            get {
                return ResourceManager.GetString("Property_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes on request.
        /// </summary>
        public static string Property_SpecialRequest {
            get {
                return ResourceManager.GetString("Property_SpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Property_Status {
            get {
                return ResourceManager.GetString("Property_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Property_Store {
            get {
                return ResourceManager.GetString("Property_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Cities.
        /// </summary>
        public static string Property_StoreCities {
            get {
                return ResourceManager.GetString("Property_StoreCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Countries.
        /// </summary>
        public static string Property_StoreCountries {
            get {
                return ResourceManager.GetString("Property_StoreCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string Property_StoreCurrency {
            get {
                return ResourceManager.GetString("Property_StoreCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Store Tags.
        /// </summary>
        public static string Property_StoreTags {
            get {
                return ResourceManager.GetString("Property_StoreTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Admins.
        /// </summary>
        public static string Property_StoreUsers {
            get {
                return ResourceManager.GetString("Property_StoreUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Property_Symbol {
            get {
                return ResourceManager.GetString("Property_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Property_TableName {
            get {
                return ResourceManager.GetString("Property_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Tags.
        /// </summary>
        public static string Property_Tags {
            get {
                return ResourceManager.GetString("Property_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Property_TimeStamp {
            get {
                return ResourceManager.GetString("Property_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Property_Title {
            get {
                return ResourceManager.GetString("Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Property_Total {
            get {
                return ResourceManager.GetString("Property_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Property_Type {
            get {
                return ResourceManager.GetString("Property_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belong To.
        /// </summary>
        public static string Property_UpperCategories {
            get {
                return ResourceManager.GetString("Property_UpperCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Property_User {
            get {
                return ResourceManager.GetString("Property_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string Property_UserName {
            get {
                return ResourceManager.GetString("Property_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worth.
        /// </summary>
        public static string Property_Worth {
            get {
                return ResourceManager.GetString("Property_Worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed.
        /// </summary>
        public static string Status_Freezed {
            get {
                return ResourceManager.GetString("Status_Freezed", resourceCulture);
            }
        }
    }
}
